---
- name: "Play 1: Update object-group csg-ftp1_customers sftp"
  hosts: ecom-firewalls
  tasks:
    - name: "Task 1: Save running-config"
      asa_command:
        - show running-config
      register: config_output
    - debug:
        var: config_output.stdout_lines
...
